# configuration section for nose
[nosetests]
verbosity = 1
detailed-errors = 1

# configuration for flake8
[flake8]
# W293: whitespace on blank lines is ok
ignore = W293,E731
# Raise the default 79 limit
max-line-length = 90
# Ignore some well known paths
exclude = .venv,.tox,dist,doc,build,*.egg


# Tox configuration
[tox]
minversion = 1.6
skipsdist = True
# List the environment that will be run by default
envlist = flake8, py34

[testenv]
# Default configuration. py26 and py27 will end up using this
setenv = VIRTUAL_ENV={envdir}
# Passed to 'pip install --pre', that will install the dependencies listed in those files
deps = -r{toxinidir}/requirements.txt
       -r{toxinidir}/test-requirements.txt
commands =
     nosetests

# Settings specific to the flake8 environment
[testenv:flake8]
# The command to run:
basepython = python3.4
commands = flake8
# We only need flake8 when linting, we do not care about the project dependencies
deps = flake8

[testenv:venv]
# Let you pass additional arguments when invoking tox
commands = {posargs}